include:
  - project: francearchives/infra
    file: gitlab-ci/gitlab-ci.yml
  - project: francearchives/infra
    file: gitlab-ci/gitlab-ci-edition.yml

deploy_livraisoncontinue:
  environment:
    url: https://livraisoncontinue-cms.francearchives.demo.logilab.fr
  script:
    - ./deploy.sh ../../../env.example

image_build_antivirus:
  stage: build
  only:
    - branch/integration
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile.antivirus
      --destination $CI_REGISTRY_IMAGE/antivirus:$CI_COMMIT_HG_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE/antivirus:latest
  needs: []

image_build_livraisoncontinue:
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_HG_SHORT_SHA
      --build-arg CONSULTATION_IMAGE=$CI_REGISTRY/francearchives/cubicweb-francearchives
      --build-arg CONSULTATION_TAG=latest-integration
